FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json .
RUN npm ci
COPY src src
COPY tsconfig.json tsconfig.json
RUN npm run build

#this helps to lower the dependencies and only use prod dependencies
FROM node:22-alpine AS lessdependencies
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production


FROM gcr.io/distroless/nodejs22
WORKDIR /app
COPY --from=lessdependencies /app/node_modules node_modules
COPY --from=build /app/dist dist

ENV PORT=3000

CMD ["dist/index.js"]



